<?php
/**
 * CloudRight payment processing service.
 *
 * @copyright Copyright (c) CloudRight
 */
declare(strict_types=1);

namespace CloudRight\Payments\Model;

use CloudRight\Payments\Api\PaymentInterface;
use Psr\Log\LoggerInterface;

/**
 * Test/development implementation of the CloudRight payment service
 * contract.
 *
 * This class intentionally does NOT talk to any real payment gateway.
 * It only validates and records the dummy transaction id generated by
 * the storefront JavaScript (CLOUDRIGHT-DUMMY-{timestamp}).
 *
 * A future version can replace the body of processPayment() with a real
 * call to the CloudRight payment API (e.g. via \Magento\Framework\HTTP\Client
 * or an HTTP client injected through the constructor) without any change
 * being required in the code that depends on PaymentInterface.
 */
class Payment implements PaymentInterface
{
    /**
     * Recognised prefix for the development/test transaction ids generated
     * by the CloudRight checkout JavaScript.
     */
    private const TEST_TRANSACTION_PREFIX = 'CLOUDRIGHT-DUMMY-';

    /**
     * @var LoggerInterface
     */
    private LoggerInterface $logger;

    /**
     * @param LoggerInterface $logger
     */
    public function __construct(LoggerInterface $logger)
    {
        $this->logger = $logger;
    }

    /**
     * @inheritDoc
     */
    public function processPayment(int $orderId, string $transactionId): string
    {
        if (!$this->isValidTransactionId($transactionId)) {
            $this->logger->warning(
                'CloudRight: rejected malformed transaction id for order.',
                ['order_id' => $orderId, 'transaction_id' => $transactionId]
            );

            return self::STATUS_FAILED;
        }

        // Test/development mode: any well-formed CLOUDRIGHT-DUMMY-* id is
        // treated as a successful authorization. The transaction id from
        // the browser is never treated as proof of a real captured
        // payment beyond this development context.
        $this->logger->info(
            'CloudRight: recorded test transaction for order.',
            ['order_id' => $orderId, 'transaction_id' => $transactionId]
        );

        return self::STATUS_PAID;
    }

    /**
     * @inheritDoc
     */
    public function isValidTransactionId(string $transactionId): bool
    {
        $transactionId = trim($transactionId);

        if ($transactionId === '') {
            return false;
        }

        // Accept the dev/test format, but also allow a generic alphanumeric
        // transaction id shape so this validator keeps working once a real
        // gateway (with its own id format) is wired in later.
        if (strpos($transactionId, self::TEST_TRANSACTION_PREFIX) === 0) {
            return (bool)preg_match('/^' . preg_quote(self::TEST_TRANSACTION_PREFIX, '/') . '\d+$/', $transactionId);
        }

        return (bool)preg_match('/^[A-Za-z0-9\-_]{6,64}$/', $transactionId);
    }
}
